version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: DreamWorld
      MYSQL_USER: steve
      MYSQL_PASSWORD: stevedarius
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../dataBase:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    command: npm start

volumes:
  mariadb_data:
