version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: steve
      MYSQL_PASSWORD: stevedarius
    volumes:
      - db_data:/var/lib/mysql
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: steve
      MYSQL_PASSWORD: stevedarius

volumes:
  db_data:
