# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # VM Web
  config.vm.define "web-server" do |web|
    web.vm.hostname = "web-server"
    web.vm.box = "chavinje/fr-bull-64"
    web.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: true
    
    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "web-server"]
      v.customize ["modifyvm", :id, "--groups", "/Projet-React"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--memory", "2048"]  # Modification de la mémoire en utilisant une chaîne de caractères
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    end

    web.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
      sleep 3
      service ssh restart
    SHELL

    web.vm.provision "shell", path: "scripts/install_sys.sh"
    web.vm.provision "shell", path: "scripts/install_web.sh"
    web.vm.provision "shell", path: "scripts/install_myadmin.sh"
    web.vm.provision "shell", path: "scripts/install_bdd.sh"  # La variable "bdd" n'est pas définie ici, utilisez "web" à la place
  end

end
